CREATE TABLE IF NOT EXISTS END_CONTRACT(number_end text, END_DATE text, INS_NM text, INS_BIRTH text, PLNR_NM text, PLNR_BIRTH text);
CREATE TABLE IF NOT EXISTS NEW_CONTRACT(number_new text, NEW_DATE text, INS_NM text, INS_BIRTH text, PLNR_NM text, PLNR_BIRTH text);

CREATE INDEX idx_end_contract ON END_CONTRACT(MUMBER_END, END_DATE, INS_NM, INS_BIRTH, PLNR_NM, PLNR_BIRTH);
CREATE INDEX idx_new_contract ON NEW_CONTRACT(MUMBER_NEW, NEW_DATE, INS_NM, INS_BIRTH, PLNR_NM, PLNR_BIRTH);
